version: '3.8'

services:
  backend:
    build: .
    container_name: backend
    env_file:
      - .env
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - /app/node_modules
      - ./public/uploads:/app/public/uploads 
    command: sh -c "npm run build && npm start"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: backend
    restart: always

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
    restart: always

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: diary
    volumes:
      - mysql_data:/var/lib/mysql
      - ./nas/diary_2025-06-29_214743.sql:/docker-entrypoint-initdb.d/diary_2025-06-29_214743.sql:ro
    restart: always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    restart: always

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.0
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    restart: always

  fluentd:
    image: fluent/fluentd:v1.14
    container_name: fluentd
    build:
      context: ./fluentd
    volumes:
      - ./fluentd/fluent.conf:/fluentd/etc/fluent.conf
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/log:/var/log:ro
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    depends_on:
      - elasticsearch
    restart: always

volumes:
  mysql_data:
  esdata:
