version: '3.8'

services:
  backend:
    build: .
    container_name: backend
    env_file:
      - .env
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - /app/node_modules
      - ./public/uploads:/app/public/uploads 
    command: sh -c "npm run build && npm start"
    restart: always

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
    restart: always

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: diary
    volumes:
      - mysql_data:/var/lib/mysql
      - ./nas/diary_2025-06-29_214743.sql:/docker-entrypoint-initdb.d/diary_2025-06-29_214743.sql:ro
    restart: always

volumes:
  mysql_data: